/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.util.ArrayList;
import utils.CurrentUser;

/**
 *
 * @author roman
 */
public class Home extends javax.swing.JFrame {
    //ErrList
    private ArrayList<String> err_list = new ArrayList<String>();
    private Error_Handling err = new Error_Handling(err_list);
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        if(!err.isMainHere()){
                System.out.println("Need to hide");
                btnAddAdmin.setEnabled(false);
                btnAdminOperation.setEnabled(false);
        }
        StringBuilder sb = new StringBuilder(CurrentUser.getInstance().getStatus());
        sb.setCharAt(0, Character.toUpperCase(sb.charAt(0)));
        CurrentUser.getInstance().setStatus(sb.toString());
        
        lbName.setText(CurrentUser.getInstance().getName());
        lbStatus.setText(CurrentUser.getInstance().getStatus());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddStudent = new javax.swing.JButton();
        btnStudentOperation = new javax.swing.JButton();
        btnStudentList = new javax.swing.JButton();
        btnAddAdmin = new javax.swing.JButton();
        btnAdminOperation = new javax.swing.JButton();
        btnAdminList = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        lbName1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lbName2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lbName3 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lbName4 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lbName5 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        lbName6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbStatus1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(134, 122, 206));

        btnAddStudent.setForeground(new java.awt.Color(36, 42, 55));
        btnAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_group_add_24px.png"))); // NOI18N
        btnAddStudent.setBorder(null);
        btnAddStudent.setBorderPainted(false);
        btnAddStudent.setFocusPainted(false);
        btnAddStudent.setFocusable(false);
        btnAddStudent.setMaximumSize(new java.awt.Dimension(40, 40));
        btnAddStudent.setMinimumSize(new java.awt.Dimension(40, 40));
        btnAddStudent.setPreferredSize(new java.awt.Dimension(40, 40));
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnStudentOperation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_low_priority_24px.png"))); // NOI18N
        btnStudentOperation.setBorder(null);
        btnStudentOperation.setBorderPainted(false);
        btnStudentOperation.setFocusPainted(false);
        btnStudentOperation.setFocusable(false);
        btnStudentOperation.setMaximumSize(new java.awt.Dimension(40, 40));
        btnStudentOperation.setMinimumSize(new java.awt.Dimension(40, 40));
        btnStudentOperation.setPreferredSize(new java.awt.Dimension(40, 40));
        btnStudentOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentOperationActionPerformed(evt);
            }
        });

        btnStudentList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 2.png"))); // NOI18N
        btnStudentList.setBorder(null);
        btnStudentList.setBorderPainted(false);
        btnStudentList.setFocusPainted(false);
        btnStudentList.setFocusable(false);
        btnStudentList.setMaximumSize(new java.awt.Dimension(40, 40));
        btnStudentList.setMinimumSize(new java.awt.Dimension(40, 40));
        btnStudentList.setPreferredSize(new java.awt.Dimension(40, 40));
        btnStudentList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentListActionPerformed(evt);
            }
        });

        btnAddAdmin.setForeground(new java.awt.Color(36, 42, 55));
        btnAddAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 6.png"))); // NOI18N
        btnAddAdmin.setBorder(null);
        btnAddAdmin.setBorderPainted(false);
        btnAddAdmin.setFocusPainted(false);
        btnAddAdmin.setFocusable(false);
        btnAddAdmin.setMaximumSize(new java.awt.Dimension(40, 40));
        btnAddAdmin.setMinimumSize(new java.awt.Dimension(40, 40));
        btnAddAdmin.setPreferredSize(new java.awt.Dimension(40, 40));
        btnAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdminActionPerformed(evt);
            }
        });

        btnAdminOperation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_low_priority_24px.png"))); // NOI18N
        btnAdminOperation.setBorder(null);
        btnAdminOperation.setBorderPainted(false);
        btnAdminOperation.setFocusPainted(false);
        btnAdminOperation.setFocusable(false);
        btnAdminOperation.setMaximumSize(new java.awt.Dimension(40, 40));
        btnAdminOperation.setMinimumSize(new java.awt.Dimension(40, 40));
        btnAdminOperation.setPreferredSize(new java.awt.Dimension(40, 40));
        btnAdminOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminOperationActionPerformed(evt);
            }
        });

        btnAdminList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 3.png"))); // NOI18N
        btnAdminList.setBorder(null);
        btnAdminList.setBorderPainted(false);
        btnAdminList.setFocusPainted(false);
        btnAdminList.setFocusable(false);
        btnAdminList.setMaximumSize(new java.awt.Dimension(40, 40));
        btnAdminList.setMinimumSize(new java.awt.Dimension(40, 40));
        btnAdminList.setPreferredSize(new java.awt.Dimension(40, 40));
        btnAdminList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminListActionPerformed(evt);
            }
        });

        lbName1.setFont(new java.awt.Font("Sitka Text", 0, 20)); // NOI18N
        lbName1.setForeground(new java.awt.Color(255, 255, 255));
        lbName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName1.setText("Add new student");
        lbName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                execute_button(evt);
            }
        });

        lbName2.setFont(new java.awt.Font("Sitka Text", 0, 20)); // NOI18N
        lbName2.setForeground(new java.awt.Color(255, 255, 255));
        lbName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName2.setText("Update\\remove student data");

        lbName3.setFont(new java.awt.Font("Sitka Text", 0, 20)); // NOI18N
        lbName3.setForeground(new java.awt.Color(255, 255, 255));
        lbName3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName3.setText("Student List");

        lbName4.setFont(new java.awt.Font("Sitka Text", 0, 20)); // NOI18N
        lbName4.setForeground(new java.awt.Color(255, 255, 255));
        lbName4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName4.setText("Add new Admin");

        lbName5.setFont(new java.awt.Font("Sitka Text", 0, 20)); // NOI18N
        lbName5.setForeground(new java.awt.Color(255, 255, 255));
        lbName5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName5.setText("Update Admin Data");

        lbName6.setFont(new java.awt.Font("Sitka Text", 0, 20)); // NOI18N
        lbName6.setForeground(new java.awt.Color(255, 255, 255));
        lbName6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName6.setText("Admin list");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminList, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentList, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator3)
                        .addComponent(lbName1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator4)
                        .addComponent(lbName2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator5)
                        .addComponent(lbName3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator6)
                        .addComponent(lbName4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator7)
                        .addComponent(lbName5, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator8)
                        .addComponent(lbName6, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnAddStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(lbName1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnStudentOperation, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbName2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnStudentList, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbName3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addComponent(btnAddAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbName4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addComponent(btnAdminOperation, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbName5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbName6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdminList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_account_circle_24px.png"))); // NOI18N

        lbName.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        lbName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbName.setText("Name");

        lbStatus.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStatus.setText("Status");

        btnEdit.setBackground(new java.awt.Color(134, 122, 206));
        btnEdit.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit Password");
        btnEdit.setFocusPainted(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(89, 106, 132));

        jSeparator2.setBackground(new java.awt.Color(89, 106, 132));

        lbStatus1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lbStatus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStatus1.setText("Admin Type:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(lbName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbStatus1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addGap(42, 42, 42)
                .addComponent(lbName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbStatus1)
                .addGap(5, 5, 5)
                .addComponent(lbStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("More");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Guide");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        menuItemAbout.setText("About");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(659, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        setVisible(false);
        Home home_form = new Home();
        home_form.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        setVisible(false);
        addStudent add_form = new addStudent();
        add_form.setVisible(true);
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
        if(!err.isMainHere()){
                err.Print_Errors();
        }else{
            setVisible(false);
            addAdmin add_form = new addAdmin();
            add_form.setVisible(true);
        }
        
    }//GEN-LAST:event_btnAddAdminActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        setVisible(false);
        GuidePage about_form = new GuidePage();
        about_form.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        setVisible(false);
        Login login_form = new Login();
        login_form.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnStudentListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentListActionPerformed
        setVisible(false);
        showStudents list_form = new showStudents();
        list_form.setVisible(true);
    }//GEN-LAST:event_btnStudentListActionPerformed

    private void btnStudentOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentOperationActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Student_Operations studOperations_form = new Student_Operations();
        studOperations_form.setVisible(true);
        
    }//GEN-LAST:event_btnStudentOperationActionPerformed

    private void btnAdminOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminOperationActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Admin_Operations operations = new Admin_Operations();
        operations.setVisible(true);
    }//GEN-LAST:event_btnAdminOperationActionPerformed

    private void btnAdminListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminListActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        showAdmins list_form = new showAdmins();
        list_form.setVisible(true);
    }//GEN-LAST:event_btnAdminListActionPerformed

    private void execute_button(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_execute_button
        // TODO add your handling code here:
    }//GEN-LAST:event_execute_button

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        Edit_Password edit_form = new Edit_Password();
        edit_form.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        About about_form = new About();
        about_form.setVisible(true);
    }//GEN-LAST:event_menuItemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnAdminList;
    private javax.swing.JButton btnAdminOperation;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnStudentList;
    private javax.swing.JButton btnStudentOperation;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName1;
    private javax.swing.JLabel lbName2;
    private javax.swing.JLabel lbName3;
    private javax.swing.JLabel lbName4;
    private javax.swing.JLabel lbName5;
    private javax.swing.JLabel lbName6;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbStatus1;
    private javax.swing.JMenuItem menuItemAbout;
    // End of variables declaration//GEN-END:variables
}
